# Generated by Django 3.2.7 on 2021-09-23 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='liked_email',
            field=models.ManyToManyField(blank=True, default=list, null=True, related_name='liked_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
