# Generated by Django 3.2.7 on 2021-09-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='liked_email',
            new_name='liked_users',
        ),
    ]
